#!/usr/bin/env node

/**
 * Cloudflare Workers AI Deployer
 *
 * Deploys an OpenAI-compatible Worker backed by Cloudflare Workers AI.
 *
 * Usage:
 *   node deploy.js           # Deploy
 *   node deploy.js --dry-run # Preview without deploying
 */

require('dotenv').config();
const Cloudflare = require('cloudflare').default;
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const config = require('./config');

const ENV_PATH = path.join(__dirname, '.env');

// Auto-generate API_KEY on first deploy and persist to .env so re-deploys reuse it.
function ensureApiKey() {
    if (process.env.API_KEY) return process.env.API_KEY;

    const key = crypto.randomBytes(32).toString('hex');
    let body = '';
    if (fs.existsSync(ENV_PATH)) {
        body = fs.readFileSync(ENV_PATH, 'utf-8');
        if (body.length > 0 && !body.endsWith('\n')) body += '\n';
    }
    body += `API_KEY=${key}\n`;
    fs.writeFileSync(ENV_PATH, body);

    process.env.API_KEY = key;
    console.log('🔐 Generated new API_KEY and wrote it to .env');
    return key;
}

const API_TOKEN = process.env.CLOUDFLARE_API_TOKEN;
const ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID;

const client = new Cloudflare({ apiToken: API_TOKEN });

const args = process.argv.slice(2);
const isDryRun = args.includes('--dry-run');

async function main() {
    console.log('🚀 Cloudflare Workers AI Deployer\n');

    if (!isDryRun && (!API_TOKEN || !ACCOUNT_ID)) {
        console.error('❌ Missing required environment variables:');
        if (!API_TOKEN) console.error('   - CLOUDFLARE_API_TOKEN');
        if (!ACCOUNT_ID) console.error('   - CLOUDFLARE_ACCOUNT_ID');
        console.error('\nCopy .env.example to .env and fill in your credentials.');
        process.exit(1);
    }

    const apiKey = isDryRun ? (process.env.API_KEY || '<auto-generated on real deploy>') : ensureApiKey();

    if (!isDryRun) {
        console.log('🔑 Verifying API token...');
        const isValid = await verifyToken();
        if (!isValid) {
            console.error('❌ Invalid API token. Please check your credentials.');
            process.exit(1);
        }
        console.log('✅ API token verified\n');
    }

    const workerName = config.workerName;
    const models = JSON.parse(fs.readFileSync(path.join(__dirname, 'models.json'), 'utf-8'));

    console.log(`📦 Deploying worker '${workerName}'${isDryRun ? ' (DRY RUN)' : ''}`);
    console.log('   Models:');
    for (const [type, id] of Object.entries(models)) {
        console.log(`     ${type.padEnd(16)} → ${id}`);
    }
    console.log();

    try {
        await deployWorker(workerName, models, apiKey);
        console.log('   ✅ Deployed successfully');
    } catch (error) {
        console.log(`   ❌ Failed: ${error.message}`);
        process.exit(1);
    }

    if (isDryRun) {
        console.log('\n✨ Dry run complete.');
        return;
    }

    const baseUrl = `https://${workerName}.${await getWorkersSubdomain()}.workers.dev/v1`;

    console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('🌐 Your endpoint is live\n');
    console.log(`   Base URL:        ${baseUrl}`);
    console.log(`   Bearer API key:  ${apiKey}`);
    console.log('\n   Quick test:');
    if (models.chat) {
        console.log(`     curl ${baseUrl}/chat/completions \\`);
        console.log(`       -H "Authorization: Bearer ${apiKey}" \\`);
        console.log(`       -H "Content-Type: application/json" \\`);
        console.log(`       -d '{"model":"chat","messages":[{"role":"user","content":"hi"}]}'`);
    } else {
        console.log(`     curl ${baseUrl}/models -H "Authorization: Bearer ${apiKey}"`);
    }
    console.log('\n✨ Done!');
}

// The workers.dev host uses the account's registered subdomain, not the
// account id. Fall back to the id only if the lookup fails.
async function getWorkersSubdomain() {
    try {
        const res = await client.workers.subdomains.get({ account_id: ACCOUNT_ID });
        if (res && res.subdomain) return res.subdomain;
    } catch {
        /* fall through */
    }
    return ACCOUNT_ID;
}

async function verifyToken() {
    try {
        const response = await client.accounts.tokens.verify({ account_id: ACCOUNT_ID });
        return response.status === 'active';
    } catch {
        return false;
    }
}

async function deployWorker(workerName, models, apiKey) {
    const templatePath = path.join(__dirname, 'workers', config.template);
    let script = fs.readFileSync(templatePath, 'utf-8');

    script = script.replace('"__DEPLOY_INJECT_CONFIG__"', JSON.stringify(models));

    if (isDryRun) {
        console.log(`   📄 Generated script (${script.length} bytes)`);
        return;
    }

    const bindings = [
        { type: 'ai', name: 'AI' },
        { type: 'secret_text', name: 'API_KEY', text: apiKey },
    ];

    await client.workers.scripts.update(workerName, {
        account_id: ACCOUNT_ID,
        metadata: {
            main_module: 'worker.js',
            compatibility_date: config.compatibility_date,
            bindings,
        },
        files: [new File([script], 'worker.js', { type: 'application/javascript+module' })],
    });

    await enableWorkersDevRoute(workerName);
}

async function enableWorkersDevRoute(workerName) {
    try {
        await client.workers.scripts.subdomain.create(workerName, {
            account_id: ACCOUNT_ID,
            enabled: true,
        });
    } catch (error) {
        console.log(`   ⚠️  Could not enable workers.dev route: ${error.message}`);
    }
}

main().catch((error) => {
    console.error('❌ Unexpected error:', error.message);
    process.exit(1);
});
